[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  CI = "false"

[[redirects]]
  from = "/api/*"
  to = "http://13.204.88.141:8080/api/:splat"
  status = 200
  force = true

