export const defaultStaticServices = [
  { id: "pdf-services", name: "PDF Services" },
  { id: "software-keys", name: "Software Keys" },
  { id: "msme", name: "MSME" },
  { id: "ration-card", name: "Ration Card" },
  { id: "gst", name: "GST" },
  { id: "aadhaar-card-address", name: "Adhaar Card (Adress Correction)" },
  { id: "can-edit", name: "CAN EDIT" },
  { id: "rto-services", name: "RTO Services" },
  { id: "registration-dept", name: "பதிவு துறை" },
  { id: "voter-id", name: "Voter ID" },
  { id: "fssai", name: "FSSAI" },
  { id: "certificate-courses", name: "Certificate Courses" },
  { id: "employment-services", name: "EMPLOYMENT SERVICES" },
  { id: "police-verification", name: "Police Verification" },
  { id: "utisl-pan", name: "Utisl Pan" },
  { id: "agri-stack-pdf", name: "Agri Stack PDF" },
  { id: "pvc-card-print", name: "PVC CARD PRINT(ALL TYPE)" },
  { id: "cm-health-card", name: "CM Health Card" },
  { id: "tnega", name: "TNEGA" },
  { id: "dharsan", name: "Dharsan" },
  { id: "pancard", name: "PanCard" },
  
  // Sub-services that need official costs before requests are made
  { id: "new-pan-card-form-49a", name: "New PAN Card (Form 49A)" },
  { id: "pan-correction-update", name: "PAN Correction / Update" },
  { id: "duplicate-pan-card", name: "Duplicate PAN Card" },
  { id: "passport-new", name: "New Passport" },
  { id: "passport-renewal", name: "Passport Renewal" },
  { id: "aadhaar-address-update", name: "Aadhaar Address Update" },
  { id: "aadhaar-mobile-update", name: "Aadhaar Mobile Update" },
  { id: "voter-id-new", name: "New Voter ID" },
  { id: "voter-id-correction", name: "Voter ID Correction" },
  { id: "ration-card-new", name: "New Ration Card" },
  { id: "ration-card-correction", name: "Ration Card Correction" },
];
