// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
<<<<<<< Updated upstream
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
=======
        "contact": {},
>>>>>>> Stashed changes
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
<<<<<<< Updated upstream
        "/wallet/recharge/gateway": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new Mugavi payment gateway order and returns the payment URL and QR code.",
=======
        "/admin/notifications": {
            "get": {
                "description": "Get a list of notifications for the Admin Panel",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get Notifications",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.Notification"
                            }
                        }
                    }
                }
            }
        },
        "/admin/requests": {
            "get": {
                "description": "Fetch all service requests simultaneously for Admin Panel",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin"
                ],
                "summary": "Get Admin Service Requests",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/handlers.ServiceApplication"
                            }
                        }
                    }
                }
            }
        },
        "/admin/retailer": {
            "post": {
                "description": "Add a new Retailer or Distributor and trigger a notification",
>>>>>>> Stashed changes
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
<<<<<<< Updated upstream
                    "Wallet"
                ],
                "summary": "Initiate Payment Gateway Recharge",
                "parameters": [
                    {
                        "description": "Gateway Recharge Request",
=======
                    "Admin"
                ],
                "summary": "Add Retailer or Distributor",
                "parameters": [
                    {
                        "description": "User Data",
>>>>>>> Stashed changes
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
<<<<<<< Updated upstream
                            "$ref": "#/definitions/wallet.GatewayRechargeRequestPayload"
=======
                            "type": "object",
                            "additionalProperties": true
>>>>>>> Stashed changes
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
<<<<<<< Updated upstream
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
=======
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/services/request": {
            "post": {
                "description": "Retailer or Distributor submits a new service request application",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Services"
                ],
                "summary": "Submit a Service Request",
                "parameters": [
                    {
                        "description": "Service Application Data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.ServiceApplication"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
>>>>>>> Stashed changes
                        }
                    }
                }
            }
        }
    },
    "definitions": {
<<<<<<< Updated upstream
        "wallet.GatewayRechargeRequestPayload": {
            "type": "object",
            "required": [
                "amount",
                "customer_email",
                "customer_mobile",
                "redirect_url"
            ],
=======
        "handlers.Notification": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isRead": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "type": {
                    "description": "\"NEW_REQUEST\", \"NEW_RETAILER\"",
                    "type": "string"
                }
            }
        },
        "handlers.ServiceApplication": {
            "type": "object",
>>>>>>> Stashed changes
            "properties": {
                "amount": {
                    "type": "number"
                },
<<<<<<< Updated upstream
                "customer_email": {
                    "type": "string"
                },
                "customer_mobile": {
                    "type": "string"
                },
                "redirect_url": {
=======
                "applicationId": {
                    "type": "string"
                },
                "createdDate": {
                    "type": "string"
                },
                "formData": {
                    "type": "object",
                    "additionalProperties": true
                },
                "retailerId": {
                    "type": "string"
                },
                "retailerName": {
                    "type": "string"
                },
                "serviceId": {
                    "type": "string"
                },
                "serviceName": {
                    "type": "string"
                },
                "status": {
>>>>>>> Stashed changes
                    "type": "string"
                }
            }
        }
<<<<<<< Updated upstream
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
=======
>>>>>>> Stashed changes
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
<<<<<<< Updated upstream
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "E-Service API",
	Description:      "This is the backend API for the E-Service platform.",
=======
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "E-Seva Platform API",
	Description:      "Backend API for E-Seva Platform managing services, retailers, and notifications.",
>>>>>>> Stashed changes
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
